export const dailyQuotes = [
  "The secret of getting ahead is getting started.",
  "The best time to plant a tree was 20 years ago. The second best time is now.",
  "It's not what we do once in a while that shapes our lives, but what we do consistently.",
  "Your future is created by what you do today, not tomorrow.",
  "Success is the sum of small efforts, repeated day in and day out.",
  "The only way to do great work is to love what you do.",
  "Don't watch the clock; do what it does. Keep going.",
  "The journey of a thousand miles begins with a single step.",
  "Either you run the day or the day runs you.",
  "Believe you can and you're halfway there.",
  "The difference between ordinary and extraordinary is that little extra.",
  "The secret to your success is found in your daily routine.",
  "Motivation is what gets you started. Habit is what keeps you going.",
  "We are what we repeatedly do. Excellence, then, is not an act, but a habit.",
  "If you want to live a happy life, tie it to a goal, not to people or things.",
  "The future depends on what you do in the present.",
  "Small daily improvements are the key to staggering long-term results.",
  "You don’t have to be great to start, but you have to start to be great.",
  "Success is not final, failure is not fatal: it is the courage to continue that counts.",
  "What you get by achieving your goals is not as important as what you become by achieving your goals.",
  "Hardships often prepare ordinary people for an extraordinary destiny.",
  "The only limit to our realization of tomorrow will be our doubts of today.",
  "I have not failed. I've just found 10,000 ways that won't work.",
  "With the new day comes new strength and new thoughts.",
  "The will to win, the desire to succeed, the urge to reach your full potential... these are the keys that will unlock the door to personal excellence.",
  "Setting goals is the first step in turning the invisible into the visible.",
  "Our greatest weakness lies in giving up. The most certain way to succeed is always to try just one more time.",
  "I can't change the direction of the wind, but I can adjust my sails to always reach my destination.",
  "The individual who says it is not possible should get out of the way of those who are doing it.",
  "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart.",
  "It does not matter how slowly you go as long as you do not stop."
];
